#+TITLE: LIVRE IV. MELPOMÈNE
#+SUBTITLE: Trad. du grec par Larcher
#+AUTHOR: Hérodote,JMC
#+EMAIL: herodote@antiquity.org,mailto:jm@lc-capital.com
#+DISTILL_AFFILIATION: Histoire grecque,None
#+DISTILL_AFFILIATION_URL: http://yahoo.com,None
#+DISTILL_BIBFILE: example.bib
#+DISTILL_APPENDIX: example-appendix.org
#+OPTIONS: toc:nil
#+OPTIONS: num:nil

* LA SCYTHIE
** I.
Après la prise de Babylone@@html:<dt-cite key="VANEMDEBOAS1989103">@@ @@html:</dt-cite>@@, Darius marcha en personne contre les Scythes. L'Asie était alors riche, très peuplée, et se trouvait dans l'état le plus florissant. Ce prince souhaitait ardemment se venger de l'insulte que les Scythes avaient faite les premiers aux Mèdes, en entrant à main armée dans leur pays, et de ce qu'après une victoire complète ils étaient devenus les maîtres de l'Asie supérieure pendant vingt-huit années, comme je l'ai dit auparavant. Ils y étaient entrés en poursuivant les Cimmériens, et en avaient enlevé l'empire aux Mèdes, qui le possédaient avant leur arrivée@@html:<dt-fn>@@ This is the /inline/ definition of this footnote@@html:</dt-fn>@@.

Après une absence de vingt-huit ans @@html:<dt-cite key="Cook2004">@@ @@html:</dt-cite>@@, les Scythes avaient voulu retourner dans leur patrie ; mais ils n'avaient pas trouvé dans cette entreprise moins de difficultés qu'ils n'en avaient rencontré en voulant pénétrer en Médie. Une armée nombreuse était allée au-devant d'eux, et leur en avait disputé l'entrée ; car leurs femmes, ennuyées de la longueur de leur absence, avaient eu commerce avec leurs esclaves.

** II.
Les Scythes crèvent les yeux à tous leurs esclaves, afin de les employer à traire le lait, dont ils font leur boisson ordinaire. Ils ont des soufflets d'os qui ressemblent à des flûtes ; ils les mettent dans les parties naturelles des juments ; les esclaves soufflent dans ces os avec la bouche, tandis que d'autres tirent le lait. Ils se servent, à ce qu'ils disent, de ce moyen parce que le souffle fait enfler les veines des juments, et baisser leur mamelle.

Lorsqu'ils ont tiré le lait, ils le versent dans des vases de bois autour desquels ils placent leurs esclaves pour le remuer et l'agiter. Ils enlèvent la partie du lait qui surnage (01), la regardant comme la meilleure et la plus délicieuse, et celle de dessous comme la moins estimée. C'est pour servir à cette fonction que les Scythes crèvent les yeux à tous leurs prisonniers ; car ils ne sont point cultivateurs, mais nomades.

* HERCULE
** VIII.
Voilà ce que les Scythes disent d'eux-mêmes, et du pays situé au-dessus du leur. Mais les Grecs, qui habitent les bords du Pont-Euxin, racontent qu'Hercule,. emmenant les troupeaux de boeufs de Géryon, arriva dans le pays occupé maintenant par les Scythes, et qui était alors désert ; que Géryon demeurait par delà le Pont, dans une île que les Grecs appellent Érythie, située près de Gades, dans l'Océan, au delà des colonnes d'Hercule. Ils prétendent aussi que l'Océan commence à l'est, et environne toute la terre de ses eaux ; mais ils se contentent de l'affirmer sans en apporter de preuves.

Ils ajoutent qu'Hercule, étant parti de ce pays, arriva dans celui qu'on connaît aujourd'hui sous le nom de Scythie ; qu'y ayant été surpris d'un orage violent et d'un grand froid, il étendit sa peau de lion, s'en enveloppa, et s'endormit ; et que ses juments, qu'il avait détachées de son char pour paître, disparurent pendant son sommeil, par une permission divine.

** IX.
Hercule les chercha à son réveil, parcourut tout le pays, et arriva enfin dans le canton appelé Hylée. Là il trouva, dans un antre, un monstre composé de deux natures, femme depuis la tête jusqu'au-dessous de la ceinture, serpent par le reste du corps. Quoique surpris en la voyant, il lui demanda si elle n'avait point vu quelque part ses chevaux. « Je les ai chez moi, lui dit-elle ; mais je ne vous les rendrai point que vous n'ayez habité avec moi. » Hercule lui accorda à ce prix ce qu'elle désirait. Cette femme différait cependant de lui remettre ses chevaux, afin de jouir plus longtemps de sa compagnie. Hercule de son côté souhaitait les recouvrer pour partir incessamment. Enfin elle les lui rendit, et lui tint en même temps ce discours : « Vos chevaux étaient venus ici ; je vous les ai gardés : j'en ai reçu la récompense. J'ai conçu de vous trois enfants. Mais que faudra-t-il que j'en fasse, quand ils seront grands ? Les établirai-je dans ce pays-ci, dont je suis la souveraine ? ou voulez-vous que je vous les envoie ? »

« Quand ces enfants auront atteint l'âge viril, lui répondit Hercule, suivant les Grecs, en vous conduisant de la manière que je vais dire, vous ne courrez point risque de vous tromper. Celui d'entre vous que vous verrez bander cet arc comme moi et se ceindre de ce baudrier comme je fais, retenez-le dans ce pays, et qu'il y fixe sa demeure. Celui qui ne pourra point exécuter les deux choses que j'ordonne, faites-le sortir du pays. Vous vous procurerez par l'a de la satisfaction, et vous ferez ma volonté. »



